language: python

env:
  - TOX_ENV=py27


# To install dependencies, tell tox to do everything but actually running the test.
install:
    - travis_retry pip install -r requirements.txt
    - travis_retry tox -e $TOX_ENV --notest

script: tox -e $TOX_ENV
